// Problem statement
// Print a Character Pattern Based on User Input

/* Description:
Write a Java program that prompts the user to enter the number of rows for a pattern. The program should then print a right-angled triangular pattern of characters. 
Each row of the triangle will start from the character 'A' and will print characters sequentially, but the starting character will depend on the current row number and 
the total number of rows specified by the user. 

For example, if the user inputs 3, the output should be: 
C
BC
ABC

This pattern is generated by starting with the last character of the sequence in the first row and prepending the previous character in the subsequent columns and rows.

*/

import java.util.Scanner;

public class PatternPrinter {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        System.out.println("Enter the total number of rows to print pattern:");
        int rows = scanner.nextInt();

        for (int row = 0; row < rows; row++) {
            for (int col = 0; col <= row; col++) {
                System.out.print((char) ('A' + rows - row + col - 1));
            }
            System.out.println();
        }
        scanner.close();
    }
}
